dist: bionic

language: cpp
addons:
  apt:
    packages:
    - clang-format-6.0
    - libgoogle-glog-dev
    - libmicrohttpd-dev

before_install:
  # Install dependencies from local scripts
  - sudo ./scripts/install_libhttpserver.sh
  - sudo ./scripts/install_librestclient-cpp.sh

jobs:
  include:
    - os: linux
      name: "Build and Tests"
      env: JOB_ENV=BuildAndTests

script:
  - ./travis.sh
