dist: bionic

language: cpp
addons:
  apt:
    packages:
    - clang-format-6.0
    - libgoogle-glog-dev
#    - libgtest-dev
    - libmicrohttpd-dev

before_install:
  - sudo ./scripts/install_libhttpserver.sh
  - sudo ./scripts/install_librestclient-cpp.sh
  # Install Google Test
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - cmake CMakeLists.txt
  - sudo make install
#  - sudo cp *.a /usr/lib
#  - sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
#  - sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a


matrix:
  include:
    - name: "Hello World build step"
      env: JOB_ENV=4711

script:
  - ./travis.sh
