dist: bionic

language: cpp

addons:
  apt:
    packages:
    - clang-format-6.0
    - libgoogle-glog-dev

matrix:
  include:
    - name: "Hello World build step"
      env: JOB_ENV=4711

script:
  - ./travis.sh
