dist: bionic
language: cpp

addons:
  apt:
    packages:
    - clang-format-6.0
    - libgoogle-glog-dev
    - libmicrohttpd-dev
    - valgrind

before_install:
  # Install dependencies from local scripts
  - test -f /usr/local/lib/libhttpserver.so ] && ./scripts/install_libhttpserver.sh
  - test -f /usr/local/lib/librestclient-cpp.so ] && ./scripts/install_librestclient-cpp.sh

before_cache:
  - sudo chown -R travis:travis /usr/local

cache:
  directories:
  - /usr/local/lib/libhttpserver.so
  - /usr/local/lib/librestclient-cpp.so
  - /usr/local/include/restclient-cpp/
  - /usr/local/include/httpserver/
  - /usr/local/include/httpserverpp
  - /usr/local/include/httpserver.hpp

jobs:
  include:
    - os: linux
      name: "Build and Unit Tests"
      env: JOB_ENV=unittest
    - os: linux
      name: "Valgrind Test"
      env: JOB_ENV=valgrind

script:
  - ./scripts/travis.sh
