dist: bionic

language: cpp
addons:
  apt:
    packages:
    - clang-format-6.0
    - libgoogle-glog-dev
    - libgtest-dev
    - libmicrohttpd-dev

before_install:
  - sudo ./scripts/install_libhttpserver.sh
  - sudo ./scripts/install_librestclient-cpp.sh

matrix:
  include:
    - name: "Hello World build step"
      env: JOB_ENV=4711

script:
  - ./travis.sh
